name: PA1417 workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
        
            - name: Install dependencies for Python
              run: |
                python -m pip install --upgrade pip
                pip install -r backend/requirements.pip

            - name: Run tests
              run: pytest --disable-warnings